# Generated by Django 4.2.1 on 2023-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-statis-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='Icone'),
        ),
    ]
