# Generated by Django 4.2.1 on 2023-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile')], max_length=13, verbose_name='Icone'),
        ),
    ]
