# Generated by Django 4.2.1 on 2023-05-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servico_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-layers', 'Camadas'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Computador'), ('lni-cog', 'Engrenagem'), ('lni-statistics', 'Formulario')], max_length=20, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Icone',
                'verbose_name_plural': 'Icones',
            },
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design')], max_length=13, verbose_name='Icone'),
        ),
    ]
