# Generated by Django 4.2.1 on 2023-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recurso_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Computador'), ('lni-statistics', 'Formulario'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Camadas'), ('lni-leaf', 'Folha')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários')], max_length=13, verbose_name='Icone'),
        ),
    ]
