# Generated by Django 4.2.1 on 2023-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cliente_estrelas_alter_recurso_icone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Computador'), ('lni-pencil-alt', 'Formulario'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico')], max_length=13, verbose_name='Icone'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
