# Generated by Django 4.2.1 on 2023-05-30 17:56

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_recurso_icone_alter_servico_icone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-layers', 'Camadas'), ('lni-laptop-phone', 'Computador'), ('lni-leaf', 'Folha'), ('lni-pencil-alt', 'Formulario'), ('lni-rocket', 'Foguete')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='Icone'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('avaliacao', models.TextField(max_length=200, verbose_name='Avaliação')),
                ('estrelas', models.CharField(choices=[('4', '4 estrelas'), ('1', '1 estrela'), ('3', '3 estrelas'), ('5', '5 estrelas'), ('2', '2 estrelas')], max_length=12, verbose_name='Estrelas')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='clientes', variations={}, verbose_name='Imagem')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
