# Generated by Django 4.2.1 on 2023-05-30 18:18

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_recurso_icone_alter_servico_icone_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estrelas',
            field=models.CharField(choices=[('4', '4 estrelas'), ('1', '1 estrela'), ('2', '2 estrelas'), ('5', '5 estrelas'), ('3', '3 estrelas')], max_length=12, verbose_name='Estrelas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='clientes', variations={'thumb': {'crop': True, 'height': 100, 'width': 100}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Camadas'), ('lni-laptop-phone', 'Computador'), ('lni-pencil-alt', 'Formulario'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=13, verbose_name='Icone'),
        ),
    ]
